### PR TITLE
 Add To-Do List Functionality with CRUD Operations

### PR DESCRIPTION
**Pull request by TshepoMagagula**
This pull request introduces a fully functional to-do list web application, allowing users to create, view, update, and delete to-do items. The app provides a clean and intuitive interface for managing daily tasks and includes essential CRUD (Create, Read, Update, Delete) functionality.

Features Added:

Create Tasks - Users can add new to-do items by entering a task name and pressing the "Add" button.
Read Tasks - All tasks are displayed in a list format with their status (completed or pending).
Update Tasks - Tasks can be marked as completed.
Delete Tasks - Users can remove tasks from the list.
Persistent Storage - Tasks are saved using an array on the server and are rendered on the page loader, so they remain available after page refresh.
Responsive Design - The application layout adjusts for both mobile and desktop devices.

Tech Stack:

Frontend: HTML, CSS, JavaScript (vanilla)
Storage: LocalStorage for persisting tasks across sessions.

How to Test:

Clone the repository and switch to this branch.
Open index.html in a browser.
Test all CRUD operations (create, mark complete, and delete) and ensure tasks persist after refreshing the page.
Confirm responsive design by testing on different screen sizes.
Screenshots: Include screenshots of the app's main views for reference.

Next Steps:

Add categories/tags for task organization.
Implement search/filter functionality for large task lists.
Notes: Feel free to provide feedback on code organization and UI/UX enhancements.

### CODE REVIEW

**Review by Sinawo — CHANGES_REQUESTED** [review]
Well done @TshepoMagagula! Can you please also include an edit button for updating tasks.

**Comment by TshepoMagagula** [comment]
> Well done @TshepoMagagula! Can also include an edit button for updating tasks.

@Sinawo your input has been noted, I am currently working on the changes. I will commit them as soon as they are complete.

**Review by NuffSaid-Bore — CHANGES_REQUESTED** [review]
@TshepoMagagula  consider proving the correctrepo clonable link in your readme.md file

**Comment by TshepoMagagula** [comment]
> @TshepoMagagula consider proving the correctrepo clonable link in your readme.md file

@NuffSaid-Bore noted, the changes will be incorporated in the next commit

**Review by zolwethu — APPROVED** [review]
@TshepoMagagula  Can we see the commits so we could move on to other things

**Review by BAHLEMAJOLA — CHANGES_REQUESTED** [review]
@TshepoMagagula Your code is well-structured! To make it easier for review and understanding, please add labels and comments. Since we're still learning Node.js, including comments will really help clarify how each part works

**Comment by TshepoMagagula** [comment]
> @TshepoMagagula Can we see the commits so we could move on to other things

@zolwethu I'll be committing the changes shortly

**Comment by TshepoMagagula** [comment]
> @TshepoMagagula Your code is well-structured! To make it easier for review and understanding, please add labels and comments. Since we're still learning Node.js, including comments will really help clarify how each part works

@BAHLEMAJOLA Alright, I'll keep that in mind for the next commit.

**Review by TshepoMagagula — COMMENTED** [review]
@zolwethu @NuffSaid-Bore I've made the requested changes please review them and provide feedback

**Review by NuffSaid-Bore — APPROVED** [review]
@TshepoMagagula i noticed you incorporated the proposed changes. Looking Good man keep up the good work!

**Review by TshepoMagagula — COMMENTED** [review]
@BAHLEMAJOLA  I have added comments to the code for readability and clarity, please review them and provide feedback.

**Review by BAHLEMAJOLA — APPROVED** [review]
Wonderful you can now merge 💯

**Review by Sinawo — APPROVED** [review]

**Pull request merged**
